on: [push]

jobs:
  dast-baseline-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: run webserver
      run: cd python/web && ifconfig && pwd && ls && python3 -m http.server &
    - name: check for open ports
      run: sudo netstat -tulpn | grep LISTEN
    #- name: Check server - 172
    #  run: curl http://172.17.0.1/index.html
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.6.1
      with:
        target: 'http://127.0.0.1:8000/index.html'
